<?php
 $aColumns = array( 'engine', 'browser', 'platform', 'version', 'grade' ); $sIndexColumn = "id"; $sTable = "ajax"; $gaSql['user'] = "root"; $gaSql['password'] = ""; $gaSql['db'] = "daemon"; $gaSql['server'] = "localhost"; $gaSql['link'] = mysql_pconnect( $gaSql['server'], $gaSql['user'], $gaSql['password'] ) or die( 'Could not open connection to server' ); mysql_select_db( $gaSql['db'], $gaSql['link'] ) or die( 'Could not select database '. $gaSql['db'] ); $sLimit = ""; if ( isset( $_GET['iDisplayStart'] ) && $_GET['iDisplayLength'] != '-1' ) { $sLimit = "LIMIT ".mysql_real_escape_string( $_GET['iDisplayStart'] ).", ". mysql_real_escape_string( $_GET['iDisplayLength'] ); } $sOrder = ""; if ( isset( $_GET['iSortCol_0'] ) ) { $sOrder = "ORDER BY  "; for ( $i=0 ; $i<intval( $_GET['iSortingCols'] ) ; $i++ ) { if ( $_GET[ 'bSortable_'.intval($_GET['iSortCol_'.$i]) ] == "true" ) { $sOrder .= $aColumns[ intval( $_GET['iSortCol_'.$i] )-1 ]."
				 	".mysql_real_escape_string( $_GET['sSortDir_'.$i] ) .", "; } } $sOrder = substr_replace( $sOrder, "", -2 ); if ( $sOrder == "ORDER BY" ) { $sOrder = ""; } } $sWhere = ""; if ( $_GET['sSearch'] != "" ) { $sWhere = "("; $aWords = preg_split('/\s+/', $_GET['sSearch']); for ( $j=0 ; $j<count($aWords) ; $j++ ) { if ( $aWords[$j] != "" ) { $sWhere .= "("; for ( $i=0 ; $i<count($aColumns) ; $i++ ) { $sWhere .= $aColumns[$i]." LIKE '%".mysql_real_escape_string( $aWords[$j] )."%' OR "; } $sWhere = substr_replace( $sWhere, "", -3 ); $sWhere .= ") AND "; } } $sWhere = substr_replace( $sWhere, "", -5 ); $sWhere .= ")"; } $sColumnWhere = ""; for ( $i=0 ; $i<count($aColumns) ; $i++ ) { if ( $_GET['sSearch_'.$i] != "" ) { $aWords = preg_split('/\s+/', $_GET['sSearch_'.$i]); $sColumnWhere .= "("; for ( $j=0 ; $j<count($aWords) ; $j++ ) { if ( $aWords[$j] != "" ) { $sColumnWhere .= $aColumns[$i]." LIKE '%".mysql_real_escape_string( $aWords[$j] )."%' OR "; } } $sColumnWhere = substr_replace( $sColumnWhere, "", -3 ); $sColumnWhere .= ") AND "; } } if ( $sColumnWhere != "" ) { $sColumnWhere = substr_replace( $sColumnWhere, "", -5 ); if ( $sWhere == "" ) { $sWhere = $sColumnWhere; } else { $sWhere .= " AND ".$sColumnWhere; } } if ( $sWhere != "" ) { $sWhere = "WHERE ".$sWhere; } $sQuery = "
		SELECT SQL_CALC_FOUND_ROWS ".str_replace(" , ", " ", implode(", ", $aColumns))."
		FROM   $sTable
		$sWhere
		$sOrder
		$sLimit
	"; $rResult = mysql_query( $sQuery, $gaSql['link'] ) or die(mysql_error()); $sQuery = "
		SELECT FOUND_ROWS()
	"; $rResultFilterTotal = mysql_query( $sQuery, $gaSql['link'] ) or die(mysql_error()); $aResultFilterTotal = mysql_fetch_array($rResultFilterTotal); $iFilteredTotal = $aResultFilterTotal[0]; $sQuery = "
		SELECT COUNT(".$sIndexColumn.")
		FROM   $sTable
	"; $rResultTotal = mysql_query( $sQuery, $gaSql['link'] ) or die(mysql_error()); $aResultTotal = mysql_fetch_array($rResultTotal); $iTotal = $aResultTotal[0]; $output = array( "sEcho" => intval($_GET['sEcho']), "iTotalRecords" => $iTotal, "iTotalDisplayRecords" => $iFilteredTotal, "aaData" => array() ); while ( $aRow = mysql_fetch_array( $rResult ) ) { $row = array(); $row[] = '<img src="img/details_open.png">'; for ( $i=0 ; $i<count($aColumns) ; $i++ ) { if ( $aColumns[$i] == "version" ) { $row[] = ($aRow[ $aColumns[$i] ]=="0") ? '-' : $aRow[ $aColumns[$i] ]; } else if ( $aColumns[$i] != ' ' ) { $row[] = $aRow[ $aColumns[$i] ]; } } $row['extra'] = 'hrmll'; $output['aaData'][] = $row; } echo json_encode( $output ); ?>