<?php
 define('IN_DAEM', true); include '../includes/init.php'; include '../templateManage/templateConfig.php'; if($_GET["action"] == "taskUpdateVersion" && !empty($_GET["checked"])) { $dataAry = array(); $query = "select * from [DRSDatabase].[dbo].[TaskEntity] WHERE ID IN (".$_GET["checked"].")"; $stmt = $conn->query( $query ); while ( $row = $stmt->fetch( PDO::FETCH_ASSOC ) ) { $pdmTaskParamAry = $pdmTaskValueAry = array(); $tmpAry = explode(";",$row["PDMParam"]); foreach($tmpAry as $kk=>$vv) { $tmpAryDepth2 = explode("=",$vv); if(!empty($tmpAryDepth2[0])) { $row["pdmHistoryTaskParamValueAry"][$tmpAryDepth2[0]] = $tmpAryDepth2[1]; } } $row["pdmNewParamValueAry"] = getWindchillPDMParamValue($row["productCodeId"]); $row["templateDataInfoAry"] = getTemplateInfo($row["templateId"]); $tmpNewParamAry = explode(",",$row["templateDataInfoAry"]["paramName"]); foreach($tmpNewParamAry as $kk=>$vv) { $row["pdmNewTaskParamValueAry"][$vv] = $row["pdmNewParamValueAry"][$vv]; } $dataAry[$row["ID"]] = $row; } $dataAryCount = count($dataAry); include template('','taskUpdateVersion'); }elseif($_GET["action"] == "postData" && !empty($_POST)) { $dataAry = $paramValueDataAry = array(); foreach($_POST as $key=>$val) { $tmpAry = explode("@@",$key); $paramValueDataAry[$tmpAry["0"]][$tmpAry["1"]] = $val; } foreach($paramValueDataAry as $key=>$val) { $sql = "select * from [DRSDatabase].[dbo].[TaskEntity] WHERE encodingMaterial = '".$key."' AND approverStatus = '1' AND status = '1'"; $query = $conn->query( $sql ); while ( $row = $query->fetch( PDO::FETCH_ASSOC ) ) { $row["uploadStatus"] = ""; $row["processStatus"] = ""; $row["builder"] = $_SESSION["UserName"]; $row["createDateTime"] = date("Y-m-d H:i:s",DAEM_TIME); $row["approverStatus"] = "0"; $row["approverDateTime"] = ""; $row["status"] = "0"; $PDMParamString = ""; foreach($paramValueDataAry[$key] as $kk=>$vv) { $PDMParamString .= $kk."=".$vv.";"; } $row["PDMParam"] = $PDMParamString; $dataAry[$key] = $row; } } foreach($dataAry as $key=>$val) { $insertSql = "INSERT INTO [DRSDatabase].[dbo].[TaskEntity]
            ([outboard],[projectId],[productCodeId],[innerProductCodeId],[innerProductModel],
             [innerProductCatalog],[innerPrintedType],[outerProductCodeId],[outerProductModel],[outerProductCatalog],
             [outerPrintedType],[certificationType],[approveType],[basicProductCode],[eer],
             [templateId],[PDMParam],[encodingMaterial],[panelColor],[panelInnerColor],
             [approver],[filePath],[filePath2],[builder],[approverStatus],
             [createDateTime],[status],[typeOf],[coolType])
             VALUES
            ('".$val['outboard']."','".$val['projectId']."','".$val['productCodeId']."','".$val['innerProductCodeId']."','".$val['innerProductModel']."',
            '".$val['innerProductCatalog']."','".$val['innerPrintedType']."','".$val['outerProductCodeId']."','".$val['outerProductModel']."','".$val['outerProductCatalog']."',
            '".$val['outerPrintedType']."','".$val['certificationType']."', '".$val['approveType']."','".$val['basicProductCode']."', '".$val['eer']."',
            '".$val['templateId']."', '".$val['PDMParam']."','".$key."', '".$val['panelColor']."','".$val['panelInnerColor']."',
            '".$val['approver']."','".$val['filePath']."', '".$val['filePath2']."', '".$val['builder']."', '0',
            '".date('Y-m-d H:i:s',DAEM_TIME)."','0','".$val['typeOf']."','".$val['coolType']."')"; $conn->query( $insertSql ); } gourl("下发新版本成功，请等待审批通过后生效!", "taskList.php?type=".$val['typeOf']); } elseif($_GET["action"] == "approve" && $_GET["ID"] >0 && $_GET["approverStatus"] >0) { $approverStatus = $_GET["approverStatus"]; $checkDataAry = array(); $sql = "select * from [DRSDatabase].[dbo].[TaskEntity] WHERE ID = '".$_GET["ID"]."'"; $query = $conn->query( $sql ); while ( $row = $query->fetch( PDO::FETCH_ASSOC ) ) { $checkDataAry = $row; } $encodingMaterial = $checkDataAry["encodingMaterial"]; if($approverStatus == '1') { $sql = "update [DRSDatabase].[dbo].[TaskEntity] set status = '2' where encodingMaterial = '".$encodingMaterial."' and approverStatus = '1' and  status = '1'"; $query = $conn->query( $sql ); if(!$query) { gourl("审批通过，但事务节点1更新失败!","",-1); } $sql = "update [DRSDatabase].[dbo].[TaskEntity] set status = '1', approverStatus = '1',approver = '".$_SESSION["UserName"]."',approverDateTime = '".date("Y-m-d H:i:s",DAEM_TIME)."' where ID = '".$_GET["ID"]."'"; $query = $conn->query( $sql ); if(!$query) { gourl("审批通过，但事务节点2更新失败!","",-1); } gourl("事务更新成功!","",-1); } elseif($approverStatus == '2' || $approverStatus == '3') { $sql = "update [DRSDatabase].[dbo].[TaskEntity] set status = '-', approverStatus = '".$approverStatus."',approver = '".$_SESSION["UserName"]."',approverDateTime = '".date("Y-m-d H:i:s",DAEM_TIME)."' where ID = '".$_GET["ID"]."'"; $query = $conn->query( $sql ); if(!$query) { gourl("操作失败!","",-1); } gourl("事务更新成功!","",-1); } } function getWindchillPDMParamValue($productCodeId) { global $db2; if(!empty($productCodeId)) { $dataAry = array(); $strSQL = "select t.parameterschname,t.academicvalue2,t.acunit from tbacvalues t where
                  t.ida3a4 in (select t1.ida2a2 from tbacs  t1 where t1.acproductnumber='" . $productCodeId . "' and t1.docislastest='1')"; $query = $db2->query($strSQL); while($row = $db2->fetch_array($query)) { foreach($row as $key=>$val) { $row[$key] = mb_convert_encoding($val,'utf-8','gb2312'); } $row["PARAMETERSCHNAME"] = str_replace(array("<",">"),array("(",")"),$row["PARAMETERSCHNAME"]); $dataAry[$row["PARAMETERSCHNAME"] . ":" . $row["ACUNIT"]] = $row["ACADEMICVALUE2"]; } return $dataAry; } } function getTemplateInfo($templateId) { global $conn; $dataAry = $tmpAry = array(); $query = "select * from [DRSDatabase].[dbo].[TemplateEntity] WHERE templateId = '".trim($templateId)."' and approverStatus ='1'"; $stmt = $conn->query( $query ); while ( $row = $stmt->fetch( PDO::FETCH_ASSOC ) ){ $tmpAry[] = $row; } foreach ($tmpAry[0] as $key=>$val) { $dataAry[$key] = $val; } return $dataAry; } 