<?php
 function get_product_catalog() { global $db2; $dataAry = array(); $sql = "SELECT CC.identifier CHILD_IDENTIFIER,A.NAME,A.CATGROUP_ID_PARENT,A.CATGROUP_ID,A.PARENTNAME,PC.IDENTIFIER PARENT_IDENTIFIER FROM (
            SELECT CHILD.CATGROUP_ID,CHILD.NAME,CATGRPREL.CATGROUP_ID_PARENT,PARENT.NAME AS PARENTNAME, LEVEL
            FROM CATGRPREL
            LEFT JOIN CATGRPDESC CHILD ON ( CHILD.CATGROUP_ID=CATGRPREL.CATGROUP_ID_CHILD AND CHILD.LANGUAGE_ID=-7)
            LEFT JOIN CATGRPDESC PARENT ON ( PARENT.CATGROUP_ID=CATGRPREL.CATGROUP_ID_PARENT AND PARENT.LANGUAGE_ID=-7)
            START WITH CATGROUP_ID_PARENT IN (SELECT CATGROUP_ID FROM CATTOGRP)
            CONNECT BY PRIOR CATGROUP_ID_CHILD = CATGROUP_ID_PARENT ORDER BY LEVEL ASC,CATGRPREL.CATGROUP_ID_PARENT DESC
            )A
            LEFT JOIN CATGROUP CC ON CC.CATGROUP_ID = A.catgroup_id LEFT JOIN CATGROUP PC ON PC.CATGROUP_ID = A.CATGROUP_ID_PARENT
            ORDER BY A.CATGROUP_ID_PARENT,A.CATGROUP_ID "; $query = $db2->query($sql); while($row = $db2->fetch_array($query)) { foreach($row as $key=>$val) { $row[$key] = iconv('gb2312','utf-8',$val); } $dataAry[] = $row; } $sortByParentAry = array(); foreach($dataAry as $key=>$val) { $sortByParentAry[$val['PARENTNAME']][$val['NAME']] = $val; } return $sortByParentAry; } function get_param_list() { global $db2; $dataAry = array(); $sql = "select distinct c.ATTR_ID,a.IDENTIFIER from catentryattr c left join attr a on a.attr_id = c.attr_id"; $query = $db2->query($sql); while($row = $db2->fetch_array($query)) { foreach($row as $key=>$val) { $row[$key] = iconv('gb2312','utf-8',$val); } $dataAry[$row['ATTR_ID']] = $row['IDENTIFIER']; } return $dataAry; } function process_data_param_into_section($paramDefineAry,$productInfoAry) { $paramSectionAry = array(); foreach($paramDefineAry as $key=>$val) { foreach($productInfoAry as $kk=>$vv) { $paramSectionAry[$key][$vv[$key]] = $vv[$key]; } } return $paramSectionAry; } function get_pic_new_code_array() { global $db2; $sql = "select * from xskuforimage"; $query = $db2->query($sql); while($row = $db2->fetch_array($query)) { foreach($row as $key=>$val) { $row[$key] = iconv('gb2312','utf-8',$val); } $dataAry[$row['PARTNUMBER']] = $row['IPARTNUMBER']; } return $dataAry; } function get_product_count_num() { global $db,$db2; $countCatgroupIdAry = array(); $sql = "select B.catgroup_id,count(*) as COUNTNUM from xcatentry A,CATGPENREL B where A.catentry_id = B.catentry_id   group by B.catgroup_id"; $query = $db2->query($sql); while($row = $db2->fetch_array($query)) { foreach($row as $key=>$val) { $row[$key] = iconv('gb2312','utf-8',$val); } $countCatgroupIdAry[$row['CATGROUP_ID']] = $row['COUNTNUM']; } $depth0Ary = $depth1Ary = $depth2Ary = array(); $sql = "select * from db_menu where m_id IN
              (select distinct m_parentid FROM db_menu
              where m_id IN
                (select distinct m_parentid from db_menu where m_url = 'product/catalog.php' and level = '2')
              and level = '1')"; $query = $db->query($sql); while($row = $db->fetch_array($query)) { $depth0Ary[$row['m_id']] = $row['m_name']; } $userPerModuleAry = get_permission_infinite_classify_sort_by_mid(''); foreach($userPerModuleAry as $key=>$val) { if(!isset($depth0Ary[$key])) { unset($userPerModuleAry[$key]); } } foreach($userPerModuleAry as $k=>$v) { foreach($v['list'] as $kk=>$vv) { foreach($vv['list'] as $kkk=>$vvv) { $cond = ''; $checkRes = stristr($vvv['m_url'],'product/catalog.php?CATGROUP_ID_PARENT='); if(count($checkRes)>0 && !empty($checkRes)) { $CATGROUP_ID_PARENT = str_replace('product/catalog.php?CATGROUP_ID_PARENT=','',$vvv['m_url']); $cond = " and PC.IDENTIFIER = '".$CATGROUP_ID_PARENT."'"; } $catalogGBK = iconv('utf-8','gb2312', $vvv['m_name']); $sql = "SELECT CC.identifier CHILD_IDENTIFIER,A.NAME,A.CATGROUP_ID_PARENT,A.CATGROUP_ID,A.PARENTNAME,PC.IDENTIFIER PARENT_IDENTIFIER FROM (
                        SELECT CHILD.CATGROUP_ID,CHILD.NAME,CATGRPREL.CATGROUP_ID_PARENT,PARENT.NAME AS PARENTNAME, LEVEL
                        FROM CATGRPREL
                        LEFT JOIN CATGRPDESC CHILD ON ( CHILD.CATGROUP_ID=CATGRPREL.CATGROUP_ID_CHILD AND CHILD.LANGUAGE_ID=-7)
                        LEFT JOIN CATGRPDESC PARENT ON ( PARENT.CATGROUP_ID=CATGRPREL.CATGROUP_ID_PARENT AND PARENT.LANGUAGE_ID=-7)
                        START WITH CATGROUP_ID_PARENT IN (SELECT CATGROUP_ID FROM CATTOGRP)
                        CONNECT BY PRIOR CATGROUP_ID_CHILD = CATGROUP_ID_PARENT ORDER BY LEVEL ASC,CATGRPREL.CATGROUP_ID_PARENT DESC
                        )A
                        LEFT JOIN CATGROUP CC ON CC.CATGROUP_ID = A.catgroup_id LEFT JOIN CATGROUP PC ON PC.CATGROUP_ID = A.CATGROUP_ID_PARENT where PARENTNAME = '".$catalogGBK."'".$cond."
                        ORDER BY A.CATGROUP_ID_PARENT,A.CATGROUP_ID "; $query = $db2->query($sql); while($row = $db2->fetch_array($query)) { foreach($row as $key=>$val) { $row[$key] = iconv('gb2312','utf-8',$val); } $userPerModuleAry[$k]['list'][$kk]['list'][$kkk]['list'][$row['CATGROUP_ID']] = $row; $userPerModuleAry[$k]['list'][$kk]['list'][$kkk]['list'][$row['CATGROUP_ID']]['countNum'] = $countCatgroupIdAry[$row['CATGROUP_ID']]; $userPerModuleAry[$k]['list'][$kk]['list'][$kkk]['series'] = count($userPerModuleAry[$k]['list'][$kk]['list'][$kkk]['list']); } } } } foreach($userPerModuleAry as $k=>$v) { foreach ($v['list'] as $kk => $vv) { $seriesCountNum = 0; foreach ($vv['list'] as $kkk => $vvv) { $parentCountNum = 0; foreach ($vvv['list'] as $kkkk => $vvvv) { $parentCountNum += $vvvv['countNum']; } $userPerModuleAry[$k]['list'][$kk]['list'][$kkk]['countNum'] = $parentCountNum; $seriesCountNum += $userPerModuleAry[$k]['list'][$kk]['list'][$kkk]['series']; } $userPerModuleAry[$k]['list'][$kk]['series'] = $seriesCountNum; } } foreach($userPerModuleAry as $k=>$v) { $seriesCountNum = 0; foreach ($v['list'] as $kk => $vv) { $parentCountNum = 0; foreach ($vv['list'] as $kkk => $vvv) { $parentCountNum += $vvv['countNum']; } $userPerModuleAry[$k]['list'][$kk]['countNum'] = $parentCountNum; $seriesCountNum += $userPerModuleAry[$k]['list'][$kk]['series']; } $userPerModuleAry[$k]['series'] = $seriesCountNum; } foreach($userPerModuleAry as $k=>$v) { $parentCountNum = 0; foreach ($v['list'] as $kk => $vv) { $parentCountNum += $vv['countNum']; } $userPerModuleAry[$k]['countNum'] = $parentCountNum; } return $userPerModuleAry; }