<?php
 define('IN_DAEM', true); include '../includes/init.php'; $type = empty($_GET["type"]) ? "outer" : $_GET["type"]; if($type == "inner") { include './templateConfigInner.php'; } $act = $_POST["act"]; if($act == "templatesComeFromAjax") { if (!empty($_POST["outboard"]) && !empty($_POST["innerProductCatalog"]) || !empty($_POST["outerProductCatalog"]) && !empty($_POST["certificationType"]) && !empty($_POST["catalog"]) && !empty($_POST["checkboxParamString"])) { $outboard = $_POST["outboard"]; $innerProductCatalog = $_POST["innerProductCatalog"]; $outerProductCatalog = $_POST["outerProductCatalog"]; $certificationType = $_POST["certificationType"]; $catalog = $_POST["catalog"]; $checkboxParamString = $_POST["checkboxParamString"]; $checkboxParamStringAry = explode(',',$checkboxParamString); $productCatalog = ""; $TemplateCatalog =""; $templateIdStr = ""; $coolType = $_POST["coolType"]; for($i=0;$i<=count($checkboxParamStringAry)-1;$i++) { if (strstr($checkboxParamStringAry[$i],"Param")) { $productCatalog = $innerProductCatalog; } else { $productCatalog = stristr($checkboxParamStringAry[$i],"Inner") ? $innerProductCatalog : $outerProductCatalog; } if (strstr($checkboxParamStringAry[$i],"MP")) { $TemplateCatalog = "铭牌"; } elseif (strstr($checkboxParamStringAry[$i],"TM")) { $TemplateCatalog = "型号标记"; } elseif (strstr($checkboxParamStringAry[$i],"EI")) { $TemplateCatalog = "欧盟信息卡"; } elseif (strstr($checkboxParamStringAry[$i],"EL")) { if($type == "inner") { $TemplateCatalog = "能效标识"; } elseif($type == "outer") { $TemplateCatalog = "能源标签"; } } elseif (strstr($checkboxParamStringAry[$i],"Param")) { $TemplateCatalog = "说明书参数页"; } $tmpGetTemplateId = ""; $sql = "select * from [DRSDatabase].[dbo].[TemplateEntity]
                    where productCatalog = '".$productCatalog."'
                    and outboard = '".$outboard."'
                    and certificate = '".$certificationType."'
                    and catalog = '".$catalog."'
                    and TemplateCatalog = '".$TemplateCatalog."'
                    and approverStatus = '1'"; if($type == 'inner') { $sql .= "and coolType = '".$coolType."'"; } $stmt = $conn->query( $sql ); while ( $row = $stmt->fetch( PDO::FETCH_ASSOC )) { $tmpGetTemplateId = $row["templateId"]; } if($tmpGetTemplateId != "") { $templateIdStr .= $tmpGetTemplateId.","; } else { echo "{\"status\":\"0\",\"data\": \" 未能找到" . $productCatalog . ":" . $TemplateCatalog . "对应模板!请返回添加或删除选项!\"}";die; } } $templateIdStr = trim($templateIdStr,","); if(!empty($templateIdStr)) { echo "{\"status\":\"1\",\"data\":\" " . $templateIdStr . "\"}";die; } else { echo "{\"status\":\"0\",\"data\": \" 未能找到" . $productCatalog . ":" . $TemplateCatalog . "对应模板!请返回添加或删除选项!\"}";die; } } else { echo "{\"status\":\"0\",\"data\": 无法获取模板参数：缺少必要参数!\"}";die; } } elseif($act == "pageTemplatesParamAjax") { if (!empty($_POST["outboard"]) && !empty($_POST["innerProductCatalog"]) || !empty($_POST["outerProductCatalog"]) && !empty($_POST["certificationType"]) && !empty($_POST["catalog"]) ) { $outboard = $_POST["outboard"]; $innerProductCatalog = $_POST["innerProductCatalog"]; $outerProductCatalog = $_POST["outerProductCatalog"]; $certificationType = $_POST["certificationType"]; $catalog = $_POST["catalog"]; $coolType = $_POST["coolType"]; $paramStringAry = array(); $paramString = ""; $sql = "select * from [DRSDatabase].[dbo].[TemplateEntity]
                    where (productCatalog = '".$innerProductCatalog."'
                    or productCatalog = '".$outerProductCatalog."')
                    and outboard = '".$outboard."'
                    and certificate = '".$certificationType."'
                    and catalog = '".$catalog."'
                    and approverStatus ='1'"; if($type == 'inner') { $sql .= "and coolType = '".$coolType."'"; } $stmt = $conn->query( $sql ); while ( $row = $stmt->fetch( PDO::FETCH_ASSOC )) { $TmpAry = explode(",",$row["paramName"]); foreach($TmpAry as $key=>$val) { if(!in_array($val,$paramStringAry)) { $paramStringAry[] = $val; $paramString .= $val.","; } } } $paramString = trim($paramString,","); echo $paramString;die; } else { echo "无法获取模板参数：缺少必要参数!"; } } elseif($act == "CheckDataIntoTemplate") { $outboard = $_POST["outboard"]; $productCatalog = $_POST["productCatalog"]; $certificate = $_POST["certificate"]; $catalog = $_POST["catalog"]; $TemplateCatalog = $_POST["TemplateCatalog"]; $coolType = $_POST["coolType"]; if (!empty($outboard) || !empty($productCatalog) || !empty($certificate) || !empty($catalog) || !empty($TemplateCatalog) ) { echo "出口，产品类，认证,类型,模板分类 不能为空!";die; } $checkDataArray = array(); $sql = "select * from [DRSDatabase].[dbo].[TemplateEntity]
                    where outboard = '".$outboard."'
                    or productCatalog = '".$productCatalog."'
                    and certificate = '".$certificate."'
                    and catalog = '".$catalog."'
                    and TemplateCatalog = '".$TemplateCatalog."'
                    and approverStatus ='1'"; $stmt = $conn->query( $sql ); while ( $row = $stmt->fetch( PDO::FETCH_ASSOC )) { $checkDataArray[] = $row; } if(count($checkDataArray) > 0) { echo "已存在：出口，产品类，认证,类型,模板分类 相同模板，请直接使用!";die; } else { echo "1";die; } } elseif($act == "getWindchillPDMParamValueAjax") { $productCodeId = $_POST["productCodeId"]; if(!empty($productCodeId)) { $returnStr = ""; $returnJson = "{"; $dataAry = array(); $strSQL = "select t.parameterschname,t.academicvalue2,t.acunit from tbacvalues t where
                  t.ida3a4 in (select t1.ida2a2 from tbacs  t1 where t1.acproductnumber='" . $productCodeId . "' and t1.docislastest='1')"; $query = $db2->query($strSQL); while($row = $db2->fetch_array($query)) { foreach($row as $key=>$val) { $row[$key] = mb_convert_encoding($val,'utf-8','gb2312'); } $row["PARAMETERSCHNAME"] = str_replace(array(" <","<",">"),array("(","(",")"),$row["PARAMETERSCHNAME"]); $row["ACADEMICVALUE2"] = str_replace(array('"'),array(""),$row["ACADEMICVALUE2"]); $dataAry[] = $row; $returnStr .= $row["PARAMETERSCHNAME"] . ":" . $row["ACADEMICVALUE2"] . "(" . $row["ACUNIT"] . ");"; $returnJson .= "\"" . $row["PARAMETERSCHNAME"] . ":" . $row["ACUNIT"] . "\":\"" . $row["ACADEMICVALUE2"] . "\","; $returnJson = str_replace(array(" <","<",">"),array("(","(",")"),$returnJson); } $returnJson = trim($returnJson,","); if (!empty($returnJson)) { $returnJson .= "}"; } echo $returnJson;die; } else { echo "无法获取模板参数：缺少必要参数!";die; } } elseif($_GET["act"] == "approve" && $_GET["ID"] >0 && $_GET["approverStatus"] >0) { $dataAry = array(); $sql = "select * from [DRSDatabase].[dbo].[TemplateEntity] where ID = '".$_GET["ID"]."'"; $query = $conn->query( $sql ); while ( $row = $query->fetch( PDO::FETCH_ASSOC ) ) { $dataAry = $row; } if(count($dataAry) == 0) gourl("未能找到该模板!","",-1); $sql = "update [DRSDatabase].[dbo].[TemplateEntity] set approverStatus = '9' where approverStatus = '1' and outboard = '".$dataAry["outboard"]."' and productCatalog = '".$dataAry["productCatalog"]."' and catalog = '".$dataAry["catalog"]."' and TemplateCatalog = '".$dataAry["TemplateCatalog"]."' and typeOf ='".$type."'"; if($type == 'inner') { $sql .= " and coolType = '".$coolType."'"; } $query = $conn->query( $sql ); if(!$query) { gourl("更新事务1失败!","",-1); } $sql = "update [DRSDatabase].[dbo].[TemplateEntity] set approverStatus = '".$_GET["approverStatus"]."',approver = '".$_SESSION["UserName"]."',approverDateTime = '".date("Y-m-d H:i:s",DAEM_TIME)."' where ID = '".$_GET["ID"]."'"; $query = $conn->query( $sql ); if(!$query) { gourl("更新事务2失败!","",-1); } gourl("事务更新成功!","",-1); } 