<?php
 define('IN_DAEM', true); include_once './init/global.php'; require_once("./init/db_mysql.php"); require_once("./init/db_oracle.php"); ini_set("max_execution_time",86400); set_time_limit(86400); $db = new db(); $db->connect($slaveDb); $ociHost = '172.74.1.19'; $ociDb['host'] = $ociHost . '/jsdoc'; $ociDb['name'] = 'kudian'; $ociDb['pass'] = 'greeic2011tw'; $db2 = new db2(); $db2->connect($ociDb); $store3ToTableConfig = array( "tw" => "BEIZHU", "gongyi" => "GONGYITUWEN", ); ob_end_clean(); echo str_pad('',1024); foreach($store3ToTableConfig as $key=>$val) { $store3 = $key; $table = $store3ToTableConfig[$store3]; $sql = "select max(date) as maxDate from BDMINFO where store3 = '".$store3."' and pb = 'WH'"; $result = $db->query_first($sql); $maxDate = $result["maxDate"]; $startDate = empty($maxDate) ? '20111001' : $maxDate; $endDate = date('Ymd'); $differ = ceil((strtotime($endDate) - strtotime($startDate))/86400); for($i=0;$i<=$differ;$i++) { $statDate = date('Ymd',strtotime($startDate)+86400*$i); $tmpAry = array(); $sql = "select to_char(t.add_time,'HH24:MI:SS') ADD_TIME1,t.* from ".$table." t where day_time = '".$statDate."' and fafangid > 5000000"; $query = $db2->query($sql); while($row = $db2->fetch_array($query)) { foreach($row as $rowKey=>$rowValue) { $row[$rowKey] = addslashes($rowValue); } $tmpAry[] = $row; } if(count($tmpAry) == 0) { echo $statDate ." is empty!!!<br />"; continue; } if($statDate == $maxDate) { $perSql = "delete from BDMINFO where date = '".$statDate."' and store3 = '".$store3."' and  pb = 'WH'"; $db->query($perSql); } $insertSql = "insert into BDMINFO (DOCNUMBER,DOCNAME,RECEPTDEPTNO,RECEPTDEPTNAME,CREATOR,
                  DATETOCOOL,ADDONSNAME,DOCSIZE,STORE2,NOTE,
                  ADDONSPATH,DATE,ITEMNUMBER,DOCNUMBERCHANGE,EXPIREDATE,
                  MADEPROUDFLAG,STORE1,ITEMGROUP,CHANGEMOULDFLAG,PDMVERSION,
                  OBJOID,STORE7,LASTUPDATE,STATE,STORE3,NEWOROLD,PB)
                  VALUES "; foreach($tmpAry as $val) { $insertSql .= "('".$val["TUHAO"]."','".addslashes($val["NAME"])."','".$val["TOUNIT"]."','".$val["TOUNITNM"]."','".$val["REN"]."',
                    '".date('Y-m-d',strtotime($val["ADD_TIME"]))." ".$val["ADD_TIME1"]."','".$val["CHANGFILE"]."','".$val["TUFU"]."','".$val["ZHONGLEI"]."','".$val["BEIZHU"]."',
                    '".$val["FILENAME"]."','".date('Ymd',strtotime($val["DAY_TIME"]))."','".$val["BIANMA"]."','".$val["CHANGENUM"]."','".$val["ENDDATE"]."',
                    '".$val["ZHIPIN"]."','".$val["SYFWEI"]."','".$val["MATERTEAM"]."','".$val["SFGM"]."','".$val["BANBENHAO"]."',
                    '".$val["PDMOBJECT"]."','".$val["QIANSHENFILE"]."','".date('Y-m-d H:i:s',DAEM_TIME)."','".$val["STATUS"]."','".$store3."','".$val["NEWOROLD"]."','WH'),"; } $insertSql = trim($insertSql,','); $res = $db->query($insertSql); if(!$res) { echo date('Y-m-d H:i:s')." --- 日期：".$statDate."<br />执行至sql：".$insertSql."<br />失败！<br /><br />";die;} echo "<span style='color: #0000ff;font-weight: bold;'>".date('Y-m-d H:i:s')." </span>--- 日期：<span style='color: green;font-weight: bold;'>".$statDate."</span>  数据表 - ".$table." ,执行同步 <span style='color: red;font-weight: bold;'> 成功！ </span> --- 共同步数据 ： <span style='color: green;font-weight: bold;'> ".count($tmpAry)."  </span> 条<br />"; flush(); } } 